
package com.projet3.library_webapp.library_webapp_model;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BookService", targetNamespace = "http://Service.webservice.projet3.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BookService {


    /**
     * 
     * @return
     *     returns java.util.List<com.projet3.library_webapp.library_webapp_model.Book>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBookList", targetNamespace = "http://Service.webservice.projet3.com/", className = "com.projet3.library_webapp.library_webapp_model.GetBookList")
    @ResponseWrapper(localName = "getBookListResponse", targetNamespace = "http://Service.webservice.projet3.com/", className = "com.projet3.library_webapp.library_webapp_model.GetBookListResponse")
    @Action(input = "http://Service.webservice.projet3.com/BookService/getBookListRequest", output = "http://Service.webservice.projet3.com/BookService/getBookListResponse")
    public List<Book> getBookList();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.projet3.library_webapp.library_webapp_model.Book
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBook", targetNamespace = "http://Service.webservice.projet3.com/", className = "com.projet3.library_webapp.library_webapp_model.GetBook")
    @ResponseWrapper(localName = "getBookResponse", targetNamespace = "http://Service.webservice.projet3.com/", className = "com.projet3.library_webapp.library_webapp_model.GetBookResponse")
    @Action(input = "http://Service.webservice.projet3.com/BookService/getBookRequest", output = "http://Service.webservice.projet3.com/BookService/getBookResponse")
    public Book getBook(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
